APP_NAME = "PortGuard AI"
APP_VERSION = "v6.0"
DEVELOPER = "Devendra Rajput"

DEFAULT_TIMEOUT = 0.5
MAX_WORKERS = 100

REPORTS_DIR = "reports"
LOGS_DIR = "logs"

DEFAULT_START_PORT = 1
DEFAULT_END_PORT = 1000